version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  prod:
    build:
      context: .
      target: production
    container_name: gothh_app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SSL_MODE=require
      - UPLOAD_THING_KEY=${UPLOAD_THING_KEY}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      - postgres

  dev:
    build:
      context: .
      target: development
    container_name: gothh_app
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: gothpgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  pgdata:
  pgadmin_data:

